language: c
matrix:
  fast_finish: true
  include:
    # Container-based 12.04 LTS Server Edition 64 bit (doesn't support 32-bit includes)
    - os: linux
      sudo: false
      env: Cmd='make -C tests test-lz4' COMPILER=cc

    - os: linux
      sudo: false
      env: Cmd="make gpptest && make clean examples && make clean cmake && make clean travis-install && make clean clangtest" COMPILER=cc

    # tag-specific test
    - if: tag =~ ^v[0-9]\.[0-9]
      os: linux
      sudo: false
      env: Cmd="echo tag is $TRAVIS_BRANCH " COMPILER=cc


script:
  - uname -a
  - echo Cmd=$Cmd
  - $COMPILER -v
  - sh -c "$Cmd"
